# spring相关配置
spring:
  # 数据库配置：url、账号、密码、连接池（druid）等
  datasource:
    username: root
    password: 652719p
    url: jdbc:mysql://localhost:3306/springboot_mybatis_demo
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    
  # FreeMarker配置  
  http:
    encoding:
      force: true
      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates

# mybatis相关配置
mybatis:
  # mybatis-config文件路径
  config-location: classpath:mybatis-config.xml
  # *Mapper.xml文件路径
  mapper-locations: classpath:com/wz/springboot/mappers/*.xml

# 在控制台输出 SQL 语句  
logging:
  level:
    com.wz.springboot.mappers: debug